name: DajeTrains
description: An app for train ticketing.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.0.0
  mobile_scanner: ^3.2.0
  get: ^4.6.5
  beacons_plugin: ^2.0.8
  intl: ^0.18.1
  flutter_local_notifications: ^14.1.1
  permission_handler: ^10.2.0
  restart_app: ^1.2.1
  rxdart: ^0.27.7
  url_launcher: ^6.1.11
  sliding_up_panel: ^2.0.0+1
  flutter_osm_plugin: ^0.55.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/train.png
